"""empty message

Revision ID: 47910f0e8d19
Revises: bccbf320766e
Create Date: 2022-06-14 12:05:51.166506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47910f0e8d19'
down_revision = 'bccbf320766e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('league', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.drop_column('league', 'max_players')
    op.drop_column('league', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('max_players', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('league', 'end_datetime')
    op.drop_column('league', 'start_time')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
